// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/db/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/db/interfaces.go -destination=internal/mocks/mock_db.go -package=mocks IPG
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPG is a mock of IPG interface.
type MockIPG struct {
	ctrl     *gomock.Controller
	recorder *MockIPGMockRecorder
	isgomock struct{}
}

// MockIPGMockRecorder is the mock recorder for MockIPG.
type MockIPGMockRecorder struct {
	mock *MockIPG
}

// NewMockIPG creates a new mock instance.
func NewMockIPG(ctrl *gomock.Controller) *MockIPG {
	mock := &MockIPG{ctrl: ctrl}
	mock.recorder = &MockIPGMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPG) EXPECT() *MockIPGMockRecorder {
	return m.recorder
}

// PingContext mocks base method.
func (m *MockIPG) PingContext(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingContext", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingContext indicates an expected call of PingContext.
func (mr *MockIPGMockRecorder) PingContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingContext", reflect.TypeOf((*MockIPG)(nil).PingContext), ctx)
}
