// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/short_link.go
//
// Generated by this command:
//
//	mockgen -source=internal/model/short_link.go -destination=internal/mocks/mock_repository.go -package=mocks IShortLinkRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/korzhev/yp-shorter/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIShortLinkRepository is a mock of IShortLinkRepository interface.
type MockIShortLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIShortLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockIShortLinkRepositoryMockRecorder is the mock recorder for MockIShortLinkRepository.
type MockIShortLinkRepositoryMockRecorder struct {
	mock *MockIShortLinkRepository
}

// NewMockIShortLinkRepository creates a new mock instance.
func NewMockIShortLinkRepository(ctrl *gomock.Controller) *MockIShortLinkRepository {
	mock := &MockIShortLinkRepository{ctrl: ctrl}
	mock.recorder = &MockIShortLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIShortLinkRepository) EXPECT() *MockIShortLinkRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIShortLinkRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIShortLinkRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIShortLinkRepository)(nil).Close))
}

// GetById mocks base method.
func (m *MockIShortLinkRepository) GetById(id string) (model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", id)
	ret0, _ := ret[0].(model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockIShortLinkRepositoryMockRecorder) GetById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockIShortLinkRepository)(nil).GetById), id)
}

// Save mocks base method.
func (m *MockIShortLinkRepository) Save(id, link string) (model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", id, link)
	ret0, _ := ret[0].(model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIShortLinkRepositoryMockRecorder) Save(id, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIShortLinkRepository)(nil).Save), id, link)
}
