// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/short_link.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/short_link.go -destination=mocks/mock_short_link.go -package=mocks IShortLinkService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/korzhev/yp-shorter/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIShortLinkService is a mock of IShortLinkService interface.
type MockIShortLinkService struct {
	ctrl     *gomock.Controller
	recorder *MockIShortLinkServiceMockRecorder
	isgomock struct{}
}

// MockIShortLinkServiceMockRecorder is the mock recorder for MockIShortLinkService.
type MockIShortLinkServiceMockRecorder struct {
	mock *MockIShortLinkService
}

// NewMockIShortLinkService creates a new mock instance.
func NewMockIShortLinkService(ctrl *gomock.Controller) *MockIShortLinkService {
	mock := &MockIShortLinkService{ctrl: ctrl}
	mock.recorder = &MockIShortLinkServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIShortLinkService) EXPECT() *MockIShortLinkServiceMockRecorder {
	return m.recorder
}

// GenerateID mocks base method.
func (m *MockIShortLinkService) GenerateID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateID indicates an expected call of GenerateID.
func (mr *MockIShortLinkServiceMockRecorder) GenerateID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateID", reflect.TypeOf((*MockIShortLinkService)(nil).GenerateID))
}

// GetByLink mocks base method.
func (m *MockIShortLinkService) GetByLink(ctx context.Context, Link string) (model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLink", ctx, Link)
	ret0, _ := ret[0].(model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLink indicates an expected call of GetByLink.
func (mr *MockIShortLinkServiceMockRecorder) GetByLink(ctx, Link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLink", reflect.TypeOf((*MockIShortLinkService)(nil).GetByLink), ctx, Link)
}

// GetByShort mocks base method.
func (m *MockIShortLinkService) GetByShort(ctx context.Context, id string) (model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShort", ctx, id)
	ret0, _ := ret[0].(model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShort indicates an expected call of GetByShort.
func (mr *MockIShortLinkServiceMockRecorder) GetByShort(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShort", reflect.TypeOf((*MockIShortLinkService)(nil).GetByShort), ctx, id)
}

// Save mocks base method.
func (m *MockIShortLinkService) Save(ctx context.Context, link string) (model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, link)
	ret0, _ := ret[0].(model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIShortLinkServiceMockRecorder) Save(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIShortLinkService)(nil).Save), ctx, link)
}

// SaveBatch mocks base method.
func (m *MockIShortLinkService) SaveBatch(ctx context.Context, batch []model.ShortLinkBatchItemRequest) ([]model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, batch)
	ret0, _ := ret[0].([]model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockIShortLinkServiceMockRecorder) SaveBatch(ctx, batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockIShortLinkService)(nil).SaveBatch), ctx, batch)
}
