// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/short_link.go
//
// Generated by this command:
//
//	mockgen -source=internal/model/short_link.go -destination=mocks/mock_repository.go -package=mocks IShortLinkRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/korzhev/yp-shorter/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIShortLinkRepository is a mock of IShortLinkRepository interface.
type MockIShortLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIShortLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockIShortLinkRepositoryMockRecorder is the mock recorder for MockIShortLinkRepository.
type MockIShortLinkRepositoryMockRecorder struct {
	mock *MockIShortLinkRepository
}

// NewMockIShortLinkRepository creates a new mock instance.
func NewMockIShortLinkRepository(ctrl *gomock.Controller) *MockIShortLinkRepository {
	mock := &MockIShortLinkRepository{ctrl: ctrl}
	mock.recorder = &MockIShortLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIShortLinkRepository) EXPECT() *MockIShortLinkRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIShortLinkRepository) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIShortLinkRepositoryMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIShortLinkRepository)(nil).Close))
}

// GetByLink mocks base method.
func (m *MockIShortLinkRepository) GetByLink(ctx context.Context, link string) (model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLink", ctx, link)
	ret0, _ := ret[0].(model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLink indicates an expected call of GetByLink.
func (mr *MockIShortLinkRepositoryMockRecorder) GetByLink(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLink", reflect.TypeOf((*MockIShortLinkRepository)(nil).GetByLink), ctx, link)
}

// GetByShort mocks base method.
func (m *MockIShortLinkRepository) GetByShort(ctx context.Context, short string) (model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByShort", ctx, short)
	ret0, _ := ret[0].(model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByShort indicates an expected call of GetByShort.
func (mr *MockIShortLinkRepositoryMockRecorder) GetByShort(ctx, short any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByShort", reflect.TypeOf((*MockIShortLinkRepository)(nil).GetByShort), ctx, short)
}

// Save mocks base method.
func (m *MockIShortLinkRepository) Save(ctx context.Context, id, link string) (model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, id, link)
	ret0, _ := ret[0].(model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockIShortLinkRepositoryMockRecorder) Save(ctx, id, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIShortLinkRepository)(nil).Save), ctx, id, link)
}

// SaveBatch mocks base method.
func (m *MockIShortLinkRepository) SaveBatch(ctx context.Context, batch []model.ShortLink) ([]model.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBatch", ctx, batch)
	ret0, _ := ret[0].([]model.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveBatch indicates an expected call of SaveBatch.
func (mr *MockIShortLinkRepositoryMockRecorder) SaveBatch(ctx, batch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBatch", reflect.TypeOf((*MockIShortLinkRepository)(nil).SaveBatch), ctx, batch)
}
