// Code generated by MockGen. DO NOT EDIT.
// Source: internal/config/db/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/config/db/interfaces.go -destination=mocks/mock_db.go -package=mocks IPG,ISQLRow,IShortLinkDB
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIPG is a mock of IPG interface.
type MockIPG struct {
	ctrl     *gomock.Controller
	recorder *MockIPGMockRecorder
	isgomock struct{}
}

// MockIPGMockRecorder is the mock recorder for MockIPG.
type MockIPGMockRecorder struct {
	mock *MockIPG
}

// NewMockIPG creates a new mock instance.
func NewMockIPG(ctrl *gomock.Controller) *MockIPG {
	mock := &MockIPG{ctrl: ctrl}
	mock.recorder = &MockIPGMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPG) EXPECT() *MockIPGMockRecorder {
	return m.recorder
}

// PingContext mocks base method.
func (m *MockIPG) PingContext(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PingContext", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// PingContext indicates an expected call of PingContext.
func (mr *MockIPGMockRecorder) PingContext(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PingContext", reflect.TypeOf((*MockIPG)(nil).PingContext), ctx)
}

// MockISQLRow is a mock of ISQLRow interface.
type MockISQLRow struct {
	ctrl     *gomock.Controller
	recorder *MockISQLRowMockRecorder
	isgomock struct{}
}

// MockISQLRowMockRecorder is the mock recorder for MockISQLRow.
type MockISQLRowMockRecorder struct {
	mock *MockISQLRow
}

// NewMockISQLRow creates a new mock instance.
func NewMockISQLRow(ctrl *gomock.Controller) *MockISQLRow {
	mock := &MockISQLRow{ctrl: ctrl}
	mock.recorder = &MockISQLRowMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISQLRow) EXPECT() *MockISQLRowMockRecorder {
	return m.recorder
}

// Scan mocks base method.
func (m *MockISQLRow) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockISQLRowMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockISQLRow)(nil).Scan), dest...)
}

// MockIShortLinkDB is a mock of IShortLinkDB interface.
type MockIShortLinkDB struct {
	ctrl     *gomock.Controller
	recorder *MockIShortLinkDBMockRecorder
	isgomock struct{}
}

// MockIShortLinkDBMockRecorder is the mock recorder for MockIShortLinkDB.
type MockIShortLinkDBMockRecorder struct {
	mock *MockIShortLinkDB
}

// NewMockIShortLinkDB creates a new mock instance.
func NewMockIShortLinkDB(ctrl *gomock.Controller) *MockIShortLinkDB {
	mock := &MockIShortLinkDB{ctrl: ctrl}
	mock.recorder = &MockIShortLinkDBMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIShortLinkDB) EXPECT() *MockIShortLinkDBMockRecorder {
	return m.recorder
}

// ExecContext mocks base method.
func (m *MockIShortLinkDB) ExecContext(ctx context.Context, query string, args ...any) (sql.Result, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExecContext", varargs...)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecContext indicates an expected call of ExecContext.
func (mr *MockIShortLinkDBMockRecorder) ExecContext(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecContext", reflect.TypeOf((*MockIShortLinkDB)(nil).ExecContext), varargs...)
}

// QueryRowContext mocks base method.
func (m *MockIShortLinkDB) QueryRowContext(ctx context.Context, query string, args ...any) *sql.Row {
	m.ctrl.T.Helper()
	varargs := []any{ctx, query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRowContext", varargs...)
	ret0, _ := ret[0].(*sql.Row)
	return ret0
}

// QueryRowContext indicates an expected call of QueryRowContext.
func (mr *MockIShortLinkDBMockRecorder) QueryRowContext(ctx, query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRowContext", reflect.TypeOf((*MockIShortLinkDB)(nil).QueryRowContext), varargs...)
}
